// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/cachedimage Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/cachedimage
//
// File is generated by gobind. Do not edit.

#ifndef __Cachedimage_H__
#define __Cachedimage_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Fscache.objc.h"
#include "Utils.objc.h"
#include "Wperr.objc.h"

@class CachedimageStruct;
@protocol CachedimageDelegate;
@class CachedimageDelegate;

@protocol CachedimageDelegate <NSObject>
- (void)onCachedImageError:(NSError* _Nullable)err;
- (void)onCachedImageSuccess:(long)id_ path:(NSString* _Nullable)path;
@end

/**
 * 	structure de la reponce de l'api
 */
@interface CachedimageStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * 		id de l image dans la bdd
 */
@property (nonatomic) long id_;
/**
 * 		le type image/jpeg | image/png
 */
@property (nonatomic) NSString* _Nonnull contentType;
/**
 * 		sa valeur md5
 */
@property (nonatomic) NSString* _Nonnull md5;
/**
 * 		la data encoder en base64
 */
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull path;
/**
 * 	permet de transformer la data de base64 a un []byte
 */
- (NSData* _Nullable)getDatas;
@end

/**
 * 	recupere un cached image depuis l'api
	de facons asynchrone
 */
FOUNDATION_EXPORT void CachedimageGet(long id_, NSString* _Nullable uri, id<CachedimageDelegate> _Nullable delegate);

/**
 * 	permet de recuperer une data d'une image directement
 */
FOUNDATION_EXPORT NSData* _Nullable CachedimageGetCache(long id_);

/**
 * 	recuperer le path dans le cache d'une image
 */
FOUNDATION_EXPORT NSString* _Nonnull CachedimageGetPath(long id_);

/**
 * 	recuperer le path dans le cache d'une image
 */
FOUNDATION_EXPORT NSString* _Nonnull CachedimageGetPathThumb(long id_);

/**
 * 	recupere un cached image depuis l'api
	de facons synchrone
 */
FOUNDATION_EXPORT CachedimageStruct* _Nullable CachedimageGetSync(long id_, NSString* _Nullable uri, NSError* _Nullable* _Nullable error);

/**
 * 	recupere un cached image depuis l'api
	de façons asynchrone
 */
FOUNDATION_EXPORT void CachedimageGetThumb(long id_, NSString* _Nullable uri, id<CachedimageDelegate> _Nullable delegate);

/**
 * 	enregistre dans le cache le l'image au format fichier
 */
FOUNDATION_EXPORT NSString* _Nonnull CachedimageSetCache(CachedimageStruct* _Nullable img);

@class CachedimageDelegate;

/**
 * 	Delegate
	protocole de reponce
	OnCachedImageError prend en paramatre une erreur
	OnCachedImageSuccess prend en parametre un path ver la photos demander
 */
@interface CachedimageDelegate : NSObject <goSeqRefInterface, CachedimageDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onCachedImageError:(NSError* _Nullable)err;
- (void)onCachedImageSuccess:(long)id_ path:(NSString* _Nullable)path;
@end

#endif
