// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/s3image Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/s3image
//
// File is generated by gobind. Do not edit.

#ifndef __S3image_H__
#define __S3image_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Fscache.objc.h"
#include "Wperr.objc.h"

@class S3imageS3PictureDownload;
@protocol S3imageDelegate;
@class S3imageDelegate;
@protocol S3imageThumbDelegate;
@class S3imageThumbDelegate;

@protocol S3imageDelegate <NSObject>
- (void)onProcessImageError:(NSError* _Nullable)p0;
- (void)onProcessImageSuccess:(BOOL)p0 p1:(NSString* _Nullable)p1;
@end

@protocol S3imageThumbDelegate <NSObject>
- (void)onProcessImageError:(NSError* _Nullable)err;
- (void)onProcessImageSuccess:(NSString* _Nullable)key path:(NSString* _Nullable)path;
@end

/**
 * 	Represente la reponce de la requette repondue par l'api
 */
@interface S3imageS3PictureDownload : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull path;
/**
 * 	Permet de transformer la valeur de la requete de la base64 en data
 */
- (NSData* _Nullable)getDatas;
@end

FOUNDATION_EXPORT void S3imageGet(NSString* _Nullable key, BOOL dropoff, id<S3imageDelegate> _Nullable delegate);

/**
 * 	Permet de recupere la valeur d'un fichier par la clee
 */
FOUNDATION_EXPORT NSData* _Nullable S3imageGetData(NSString* _Nullable key);

/**
 * 	Permet de recuperer une version thumb
 */
FOUNDATION_EXPORT void S3imageGetThumb(NSString* _Nullable key, id<S3imageThumbDelegate> _Nullable delegate);

@class S3imageDelegate;

@class S3imageThumbDelegate;

/**
 * Delegate est utilisé pour la récuperation asynchrone des images
 */
@interface S3imageDelegate : NSObject <goSeqRefInterface, S3imageDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onProcessImageError:(NSError* _Nullable)p0;
- (void)onProcessImageSuccess:(BOOL)p0 p1:(NSString* _Nullable)p1;
@end

@interface S3imageThumbDelegate : NSObject <goSeqRefInterface, S3imageThumbDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onProcessImageError:(NSError* _Nullable)err;
- (void)onProcessImageSuccess:(NSString* _Nullable)key path:(NSString* _Nullable)path;
@end

#endif
