// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/updater Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/updater
//
// File is generated by gobind. Do not edit.

#ifndef __Update_H__
#define __Update_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Config.objc.h"

@class UpdateIosResults;
@class UpdateIosStoreInfos;
@class UpdateVersion;
@protocol UpdateDelegate;
@class UpdateDelegate;

@protocol UpdateDelegate <NSObject>
- (void)onUpdateNeeded:(UpdateVersion* _Nullable)version;
@end

@interface UpdateIosResults : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long resultCount;
// skipped field IosResults.Results with unsupported type: []github.com/ProovGroup/weproov-sdk-go/updater.IosStoreInfos

@end

@interface UpdateIosStoreInfos : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field IosStoreInfos.IpadScreenshotUrls with unsupported type: []string

// skipped field IosStoreInfos.AppletvScreenshotUrls with unsupported type: []string

@property (nonatomic) NSString* _Nonnull artworkUrl60;
@property (nonatomic) NSString* _Nonnull artworkUrl512;
@property (nonatomic) NSString* _Nonnull artworkUrl100;
@property (nonatomic) NSString* _Nonnull artistViewUrl;
@property (nonatomic) BOOL isGameCenterEnabled;
@property (nonatomic) NSString* _Nonnull kind;
// skipped field IosStoreInfos.Features with unsupported type: []string

// skipped field IosStoreInfos.SupportedDevices with unsupported type: []string

// skipped field IosStoreInfos.ScreenshotUrls with unsupported type: []string

// skipped field IosStoreInfos.Advisories with unsupported type: []string

@property (nonatomic) NSString* _Nonnull trackViewUrl;
@property (nonatomic) NSString* _Nonnull trackCensoredName;
// skipped field IosStoreInfos.LanguageCodesISO2A with unsupported type: []string

@property (nonatomic) NSString* _Nonnull fileSizeBytes;
@property (nonatomic) NSString* _Nonnull sellerUrl;
@property (nonatomic) NSString* _Nonnull contentAdvisoryRating;
@property (nonatomic) NSString* _Nonnull trackContentRating;
// skipped field IosStoreInfos.GenreIds with unsupported type: []string

@property (nonatomic) NSString* _Nonnull currentVersionReleaseDate;
@property (nonatomic) NSString* _Nonnull releaseNotes;
@property (nonatomic) NSString* _Nonnull currency;
@property (nonatomic) NSString* _Nonnull wrapperType;
@property (nonatomic) NSString* _Nonnull version;
@property (nonatomic) NSString* _Nonnull description;
@property (nonatomic) long artistId;
@property (nonatomic) NSString* _Nonnull artistName;
// skipped field IosStoreInfos.Genres with unsupported type: []string

@property (nonatomic) double price;
@property (nonatomic) long trackId;
@property (nonatomic) NSString* _Nonnull trackName;
@property (nonatomic) NSString* _Nonnull bundleId;
// skipped field IosStoreInfos.ReleaseDate with unsupported type: time.Time

@property (nonatomic) BOOL isVppDeviceBasedLicensingEnabled;
@property (nonatomic) NSString* _Nonnull primaryGenreName;
@property (nonatomic) NSString* _Nonnull formattedPrice;
@property (nonatomic) long primaryGenreId;
@property (nonatomic) NSString* _Nonnull sellerName;
@property (nonatomic) NSString* _Nonnull minimumOsVersion;
@end

@interface UpdateVersion : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long major;
@property (nonatomic) long minor;
@property (nonatomic) long build;
@property (nonatomic) NSString* _Nonnull releaseNotes;
// skipped method Version.Equal with unsupported parameter or return types

// skipped method Version.NeedUpdate with unsupported parameter or return types

- (void)print;
@end

FOUNDATION_EXPORT void UpdateCheckAndroid(NSString* _Nullable bundleId, NSString* _Nullable version, id<UpdateDelegate> _Nullable delegate);

FOUNDATION_EXPORT void UpdateCheckIos(NSString* _Nullable bundleId, NSString* _Nullable version, id<UpdateDelegate> _Nullable delegate);

FOUNDATION_EXPORT UpdateVersion* _Nullable UpdateGetVersionIos(NSString* _Nullable bundleId);

@class UpdateDelegate;

@interface UpdateDelegate : NSObject <goSeqRefInterface, UpdateDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onUpdateNeeded:(UpdateVersion* _Nullable)version;
@end

#endif
