// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/affiliation Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/affiliation
//
// File is generated by gobind. Do not edit.

#ifndef __Affiliation_H__
#define __Affiliation_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Cachedimage.objc.h"
#include "Translations.objc.h"
#include "Wperr.objc.h"

@class AffiliationAffiliationCode;
@class AffiliationList;
@protocol AffiliationAffiliationCodeResponce;
@class AffiliationAffiliationCodeResponce;
@protocol AffiliationListDelegate;
@class AffiliationListDelegate;

@protocol AffiliationAffiliationCodeResponce <NSObject>
- (void)onError:(NSError* _Nullable)p0;
- (void)onSuccess:(AffiliationAffiliationCode* _Nullable)afcode;
@end

@protocol AffiliationListDelegate <NSObject>
- (void)onAffiliationFindError:(NSError* _Nullable)err;
- (void)onAffiliationFindSuccess:(AffiliationList* _Nullable)list;
@end

@interface AffiliationAffiliationCode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull code;
/**
 * Url  string `json:"url"`
Secret       string                   `json:"secret"`
 */
@property (nonatomic) long title;
// skipped field AffiliationCode.Title_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

@property (nonatomic) long description;
// skipped field AffiliationCode.Description_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

/**
 * Owner                  int                      `json:"owner"`
 */
@property (nonatomic) long logoId;
@property (nonatomic) long activationDescription;
// skipped field AffiliationCode.ActivationDescription_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

@property (nonatomic) long removeDescription;
// skipped field AffiliationCode.RemoveDescription_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

@property (nonatomic) NSString* _Nonnull email;
@property (nonatomic) NSString* _Nonnull phone;
- (NSString* _Nonnull)getActivationDescriptionTr;
- (NSString* _Nonnull)getDescriptionTr;
- (void)getLogo:(id<CachedimageDelegate> _Nullable)delegate;
- (NSString* _Nonnull)getRemoveDescriptionTr;
- (NSString* _Nonnull)getTitleTr;
@end

@interface AffiliationList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull find;
@property (nonatomic) long offset;
@property (nonatomic) long limit;
@property (nonatomic) BOOL haveMore;
// skipped field List.Result with unsupported type: []github.com/ProovGroup/weproov-sdk-go/affiliation.AffiliationCode

- (long)count;
- (AffiliationAffiliationCode* _Nullable)get:(long)num;
- (void)next:(id<AffiliationListDelegate> _Nullable)delegate;
@end

FOUNDATION_EXPORT void AffiliationAdd(NSString* _Nullable code, id<AffiliationAffiliationCodeResponce> _Nullable resp);

FOUNDATION_EXPORT BOOL AffiliationAddSync(NSString* _Nullable code, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AffiliationGetCode(NSString* _Nullable code, id<AffiliationAffiliationCodeResponce> _Nullable resp);

FOUNDATION_EXPORT AffiliationAffiliationCode* _Nullable AffiliationGetCodeSync(NSString* _Nullable code, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AffiliationGetList(NSString* _Nullable mType, long offset, long limit, id<AffiliationListDelegate> _Nullable delegate);

FOUNDATION_EXPORT AffiliationList* _Nullable AffiliationGetListSync(NSString* _Nullable mType, long offset, long limit, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL AffiliationHaveRightToUse(NSString* _Nullable code, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void AffiliationRemove(NSString* _Nullable code, id<AffiliationAffiliationCodeResponce> _Nullable resp);

FOUNDATION_EXPORT BOOL AffiliationRemoveSync(NSString* _Nullable code, NSError* _Nullable* _Nullable error);

@class AffiliationAffiliationCodeResponce;

@class AffiliationListDelegate;

@interface AffiliationAffiliationCodeResponce : NSObject <goSeqRefInterface, AffiliationAffiliationCodeResponce> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSError* _Nullable)p0;
- (void)onSuccess:(AffiliationAffiliationCode* _Nullable)afcode;
@end

@interface AffiliationListDelegate : NSObject <goSeqRefInterface, AffiliationListDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onAffiliationFindError:(NSError* _Nullable)err;
- (void)onAffiliationFindSuccess:(AffiliationList* _Nullable)list;
@end

#endif
