// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/translations Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/translations
//
// File is generated by gobind. Do not edit.

#ifndef __Translations_H__
#define __Translations_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Config.objc.h"

@class TranslationsTranslation;

@interface TranslationsTranslation : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull fr;
@property (nonatomic) NSString* _Nonnull en;
@property (nonatomic) NSString* _Nonnull es;
@property (nonatomic) NSString* _Nonnull pl;
@property (nonatomic) NSString* _Nonnull nl;
@property (nonatomic) NSString* _Nonnull de;
@property (nonatomic) NSString* _Nonnull it;
@property (nonatomic) NSString* _Nonnull pt;
@property (nonatomic) NSString* _Nonnull ro;
@property (nonatomic) NSString* _Nonnull sv;
@property (nonatomic) NSString* _Nonnull tr;
@property (nonatomic) NSString* _Nonnull cs;
@property (nonatomic) NSString* _Nonnull sl;
- (NSString* _Nonnull)getLang:(NSString* _Nullable)lang;
- (NSString* _Nonnull)getLocal;
@end

#endif
