
// Objective-C API for talking to the following Go packages
//
//	github.com/ProovGroup/weproov-sdk-go
//	github.com/ProovGroup/weproov-sdk-go/cachedimage
//	github.com/ProovGroup/weproov-sdk-go/category
//	github.com/ProovGroup/weproov-sdk-go/mission
//	github.com/ProovGroup/weproov-sdk-go/config
//	github.com/ProovGroup/weproov-sdk-go/keyvalue
//	github.com/ProovGroup/weproov-sdk-go/pulldownload
//	github.com/ProovGroup/weproov-sdk-go/rights
//	github.com/ProovGroup/weproov-sdk-go/s3image
//	github.com/ProovGroup/weproov-sdk-go/geoloc
//	github.com/ProovGroup/weproov-sdk-go/report
//	github.com/ProovGroup/weproov-sdk-go/templates
//	github.com/ProovGroup/weproov-sdk-go/items
//	github.com/ProovGroup/weproov-sdk-go/user
//	github.com/ProovGroup/weproov-sdk-go/utils
//	github.com/ProovGroup/weproov-sdk-go/translations
//	github.com/ProovGroup/weproov-sdk-go/updater
//	github.com/ProovGroup/weproov-sdk-go/fscache
//	github.com/ProovGroup/weproov-sdk-go/proover
//	github.com/ProovGroup/weproov-sdk-go/wperr
//	github.com/ProovGroup/weproov-sdk-go/pack
//	github.com/ProovGroup/weproov-sdk-go/team
//	github.com/ProovGroup/weproov-sdk-go/requestNative
//	github.com/ProovGroup/weproov-sdk-go/affiliation
//	github.com/ProovGroup/weproov-sdk-go/services
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wprv_FRAMEWORK_H__
#define __Wprv_FRAMEWORK_H__

#include "Wprv.objc.h"
#include "Cachedimage.objc.h"
#include "Category.objc.h"
#include "Mission.objc.h"
#include "Config.objc.h"
#include "Keyvalue.objc.h"
#include "Pulldownload.objc.h"
#include "Rights.objc.h"
#include "S3image.objc.h"
#include "Geoloc.objc.h"
#include "Report.objc.h"
#include "Templates.objc.h"
#include "Items.objc.h"
#include "User.objc.h"
#include "Utils.objc.h"
#include "Translations.objc.h"
#include "Update.objc.h"
#include "Fscache.objc.h"
#include "Proover.objc.h"
#include "Wperr.objc.h"
#include "Pack.objc.h"
#include "Team.objc.h"
#include "Rn.objc.h"
#include "Affiliation.objc.h"
#include "Services.objc.h"
#include "Universe.objc.h"

#endif
