// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/geoloc Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/geoloc
//
// File is generated by gobind. Do not edit.

#ifndef __Geoloc_H__
#define __Geoloc_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GeolocStruct;

@interface GeolocStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) double longitude;
@property (nonatomic) double altitude;
@property (nonatomic) double latitude;
@property (nonatomic) NSString* _Nonnull adress;
- (BOOL)geolocIsEmpty;
@end

// skipped function GetLastGeoloc with unsupported parameter or return types


FOUNDATION_EXPORT double GeolocLastAlt(void);

FOUNDATION_EXPORT double GeolocLastLat(void);

FOUNDATION_EXPORT double GeolocLastLng(void);

/**
 * 	permetras de sauvgarder la derniere position connu
	elle seras utiliser pour la position du rapport ainsi que pour le photos
	une nouvelle structure est initialiser pour eviter d'ecrire sur la variable a chaque modification
 */
FOUNDATION_EXPORT void GeolocSaveLastGeoloc(double longitude, double latitude, double altitude);

#endif
