// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/pack Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/pack
//
// File is generated by gobind. Do not edit.

#ifndef __Pack_H__
#define __Pack_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Cachedimage.objc.h"
#include "Translations.objc.h"
#include "User.objc.h"

@class PackPacks;
@class PackStruct;
@protocol PackDelegate;
@class PackDelegate;

@protocol PackDelegate <NSObject>
- (void)onPackError:(NSError* _Nullable)err;
- (void)onPackSuccess;
@end

@interface PackPacks : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Packs.Packs with unsupported type: []github.com/ProovGroup/weproov-sdk-go/pack.Struct

- (long)count;
- (PackStruct* _Nullable)get:(long)num;
@end

@interface PackStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull crmName;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) long title;
@property (nonatomic) long cachedId;
// skipped field Struct.Title_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

@property (nonatomic) long ask;
// skipped field Struct.Ask_ with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

// skipped field Struct.Subpack with unsupported type: []github.com/ProovGroup/weproov-sdk-go/pack.Struct

// skipped field Struct.PackIds with unsupported type: []int

- (void)addPackId:(long)id_;
- (long)countSubpack;
- (NSString* _Nonnull)getAskTr;
- (void)getImage:(id<CachedimageDelegate> _Nullable)delegate;
- (PackStruct* _Nullable)getSubpack:(long)num;
- (NSString* _Nonnull)getTitleTr;
- (BOOL)haveAsk;
- (BOOL)haveSubpack;
- (void)send:(long)val delegate:(id<PackDelegate> _Nullable)delegate;
@end

FOUNDATION_EXPORT void PackDownloadPack(id<PackDelegate> _Nullable delegate);

FOUNDATION_EXPORT PackPacks* _Nullable PackGetAlls(void);

FOUNDATION_EXPORT PackStruct* _Nullable PackNewStruct(void);

@class PackDelegate;

@interface PackDelegate : NSObject <goSeqRefInterface, PackDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onPackError:(NSError* _Nullable)err;
- (void)onPackSuccess;
@end

#endif
