// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/config Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/config
//
// File is generated by gobind. Do not edit.

#ifndef __Config_H__
#define __Config_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Fscache.objc.h"
#include "Keyvalue.objc.h"

@class ConfigEnvironment;

@interface ConfigEnvironment : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * 		Permet de savoir si le framwork est en mode production ou en mode developement

Production bool

		represent l'api prensente pour les requettes
 */
@property (nonatomic) NSString* _Nonnull baseUrl;
/**
 * 		represent l'api qui est la pour les donner stocker en cache
		principalement des images
 */
@property (nonatomic) NSString* _Nonnull cacheUrl;
@property (nonatomic) NSString* _Nonnull device;
/**
 * 		Permet de stocker la langue du telephone
		CETTE VARIABLE EST TRES IMPORTANTE
 */
@property (nonatomic) NSString* _Nonnull local;
@property (nonatomic) NSString* _Nonnull clientID;
@property (nonatomic) NSString* _Nonnull clientSecret;
/**
 * GetAuthURL retourne l'url complète vers l'api d'auth avec le chemin passé en paramètre.
 */
- (NSString* _Nonnull)getAuthURL:(NSString* _Nullable)path;
- (NSString* _Nonnull)getCacheURL:(NSString* _Nullable)path;
/**
 * 	Permet de recuperer l'url de l'api pour les requete
 */
- (NSString* _Nonnull)getUrl:(NSString* _Nullable)path;
@end

@interface Config : NSObject
/**
 * 	ATENTION LES VARIABLE PRESENTE DANS CE PACKAGE PEUVENT INFLIANCER TOUT LES AUTRE
 */
+ (ConfigEnvironment* _Nullable) env;
+ (void) setEnv:(ConfigEnvironment* _Nullable)v;

@end

FOUNDATION_EXPORT BOOL ConfigDnsIsSet(void);

/**
 * 	retourne la dernier lang enregistrer comme default
 */
FOUNDATION_EXPORT NSString* _Nonnull ConfigGetDefaultLocal(void);

FOUNDATION_EXPORT BOOL ConfigGetModeSaved(void);

FOUNDATION_EXPORT NSString* _Nonnull ConfigGetNotificationToken(void);

FOUNDATION_EXPORT BOOL ConfigIsAndroid(void);

FOUNDATION_EXPORT BOOL ConfigIsIos(void);

/**
 * 	Restor la dernier lang designer comme default comme lang actulement utiliser
 */
FOUNDATION_EXPORT void ConfigResetLocal(void);

FOUNDATION_EXPORT void ConfigSetAppAuthCredentials(NSString* _Nullable clientID, NSString* _Nullable secret);

FOUNDATION_EXPORT BOOL ConfigSetDns(NSString* _Nullable ApiUrl, NSString* _Nullable CacheUrl);

/**
 * 	Permet de signaler la langue souhaiter
	en premier parametre le lange formater 'fr', 'en', ...
	en second permet de savoir si il faut le sauvgarder dans comme lang par default
 */
FOUNDATION_EXPORT void ConfigSetLocal(NSString* _Nullable local, BOOL isDefault);

/**
 * 	Permet de saugarder le token a utiliser pour les notification push
 */
FOUNDATION_EXPORT void ConfigSetNotificationToken(NSString* _Nullable token);

FOUNDATION_EXPORT void ConfigSetVersion(NSString* _Nullable version);

FOUNDATION_EXPORT void ConfigShowDNS(void);

FOUNDATION_EXPORT NSString* _Nonnull ConfigVersion(void);

#endif
