// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/templates Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/templates
//
// File is generated by gobind. Do not edit.

#ifndef __Templates_H__
#define __Templates_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Fscache.objc.h"
#include "Translations.objc.h"
#include "Wperr.objc.h"

@class TemplatesTemplate;
@protocol TemplatesTemplateDelegate;
@class TemplatesTemplateDelegate;

@protocol TemplatesTemplateDelegate <NSObject>
- (void)onTemplateError:(NSError* _Nullable)p0;
- (void)onTemplateSuccessString:(NSString* _Nullable)p0;
@end

@interface TemplatesTemplate : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) long title;
@property (nonatomic) long description;
@property (nonatomic) BOOL dropoff;
@property (nonatomic) BOOL fullDropoff;
@property (nonatomic) BOOL autoRestart;
@property (nonatomic) BOOL showGeolocPDF;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) NSString* _Nonnull mails;
@property (nonatomic) long categoryId;
@property (nonatomic) NSString* _Nonnull restartState;
@property (nonatomic) long imageReport;
@property (nonatomic) NSString* _Nonnull pdfHeaderBackgroundColor;
@property (nonatomic) NSString* _Nonnull pdfHeaderTextColor;
@property (nonatomic) long owner;
// skipped field Template.TitleTr with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

// skipped field Template.DescriptionTr with unsupported type: github.com/ProovGroup/weproov-sdk-go/translations.Translation

- (NSString* _Nonnull)getDescriptionTr;
- (void)getFullJsonString:(BOOL)forceRefresh delegate:(id<TemplatesTemplateDelegate> _Nullable)delegate;
- (NSString* _Nonnull)getFullJsonStringSync:(BOOL)forceRefresh error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getFullJsonStringWithFieldsSync:(NSString* _Nullable)fields error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getTitleTr;
- (BOOL)haveInCache;
- (void)removeAllCache;
- (NSString* _Nonnull)serialize;
@end

FOUNDATION_EXPORT NSString* _Nonnull TemplatesGetFullJsonStringSync(BOOL forceRefresh, long id_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TemplatesGetFullJsonStringWithFieldsSync(long id_, NSString* _Nullable fields, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TemplatesTemplate* _Nullable TemplatesNewObject(NSString* _Nullable str);

@class TemplatesTemplateDelegate;

@interface TemplatesTemplateDelegate : NSObject <goSeqRefInterface, TemplatesTemplateDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onTemplateError:(NSError* _Nullable)p0;
- (void)onTemplateSuccessString:(NSString* _Nullable)p0;
@end

#endif
