// Objective-C API for talking to github.com/ProovGroup/weproov-sdk-go/utils Go package.
//   gobind -lang=objc github.com/ProovGroup/weproov-sdk-go/utils
//
// File is generated by gobind. Do not edit.

#ifndef __Utils_H__
#define __Utils_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Wperr.objc.h"

@class UtilsCryptoKey;

@interface UtilsCryptoKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable key;
@property (nonatomic) NSData* _Nullable nonce;
@end

@interface Utils : NSObject
+ (NSError* _Nullable) deleteReportFail;
+ (void) setDeleteReportFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) downloadFail;
+ (void) setDownloadFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) getReportFail;
+ (void) setGetReportFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) getTemplateFail;
+ (void) setGetTemplateFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) importItemFail;
+ (void) setImportItemFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) listReportFail;
+ (void) setListReportFail:(NSError* _Nullable)v;

+ (NSError* _Nullable) loginFail;
+ (void) setLoginFail:(NSError* _Nullable)v;

@end

FOUNDATION_EXPORT NSData* _Nullable UtilsCompressToPng(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

// skipped function Copys with unsupported parameter or return types


FOUNDATION_EXPORT BOOL UtilsCrypteRSAFile(NSString* _Nullable entry, NSString* _Nullable to, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable UtilsCrypteRsa(NSData* _Nullable data);

FOUNDATION_EXPORT NSData* _Nullable UtilsDecrypt(NSString* _Nullable key, NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL UtilsDecryptFile(NSString* _Nullable key, NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable UtilsDecrypteRsa(NSData* _Nullable data);

FOUNDATION_EXPORT NSData* _Nullable UtilsEncrypt(NSString* _Nullable key, NSData* _Nullable data, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL UtilsEncrypteFile(NSString* _Nullable key, NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull UtilsFormatCell(NSString* _Nullable cell, NSString* _Nullable localized, NSError* _Nullable* _Nullable error);

// skipped function GetCryptoKeyUser with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull UtilsGetDocumentsPath(NSString* _Nullable path);

FOUNDATION_EXPORT NSString* _Nonnull UtilsGetHomePath(void);

FOUNDATION_EXPORT NSString* _Nonnull UtilsGetOs(void);

// skipped function GetPublicKey with unsupported parameter or return types


// skipped function GetTokenData with unsupported parameter or return types


FOUNDATION_EXPORT BOOL UtilsIsValidImage(NSData* _Nullable data);

FOUNDATION_EXPORT void UtilsMkdirAll(NSString* _Nullable path);

FOUNDATION_EXPORT NSString* _Nonnull UtilsRandomString(long n);

FOUNDATION_EXPORT BOOL UtilsResizeImage(NSString* _Nullable origin, NSString* _Nullable to, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull UtilsSha1(NSData* _Nullable value);

#endif
